= Roomboo

image:https://travis-ci.org/labcabrera/roomboo.svg?branch=master["Build Status", link="https://travis-ci.org/labcabrera/roomboo"]
image:https://api.codacy.com/project/badge/Grade/018b2390426f4138aa16f2548c75f8bc["Codacy code quality", link="https://www.codacy.com/app/lab.cabrera/roomboo?utm_source=github.com&utm_medium=referral&utm_content=labcabrera/roomboo&utm_campaign=Badge_Grade"]

== Introducción

Roomboo es una aplicación de *reserva de salas de reuniones*. Este proyecto provee de una API REST
ofreciendo las siguientes funcionalidades:

* Solicitud de una reserva de sala
* Confirmación de una reserva
* Cancelación de una reserva
* Mantenimiento de entidades (empresas, edificios, salas, usuarios de la API y de la aplicación, etc).
* Consulta de alertas
* Envío de notificaciones

== Requisitos

* JDK8+
* MongoDB

== Docker

La imagen de docker se puede encontrar en:

https://hub.docker.com/r/labcabrera/roomboo-api/

Para ejecutarla simplemente tendremos que ejecutar:

----
docker pull labcabrera/roomboo-api

docker run -i -p 8080:8080 -t labcabrera/roomboo-api
----

Argumentos:

[options="headers"]
|===
|Nombre                    | Valor por defecto | Descripción
| `PORT`                   | _8080_            | Puerto de la aplicación.
| `SPRING_PROFILES_ACTIVE` | _local_           | Perfil de Spring.
| `ENV_MONGO_HOST`         | localhost         | Nombre del host de MongoDB.
|`ENV_SMTP_USERNAME`       | _undefined_       | Usuario de envío de correo.
|`ENV_SMTP_PASSWORD`       | _undefined_       | Password de envío de correo.
|`ENV_SMTP_HOST`           | _smtp.gmail.com_  | Servidor de correo
|`ENV_SMTP_PORT`           | _587_             |
|===

Por ejemplo, para ejecutar la aplicación en el puerto 8000 con el perfil sin seguridad ejecutaremos:

----
docker run -i -p 8000:8000 -t \
  -e ENV_MONGO_HOST='172.17.0.2' \
  -e PORT='8000' \
  -e SPRING_PROFILES_ACTIVE='local,unsecured' \
  labcabrera/roomboo-api
----

En el caso de ejecutar la aplicación contra una imagen local de MongoDB deberemos obtener la IP que tiene utilizando el comando

----
docker network inspect ${network} 
----

obteniendo una salida similar a la siguiente:

[source,json]
----
	"Containers": {
	    "db94ced0c3dd621f1ef71dd648dce23c6aec5ae4adbf26e1ab98764c73122b74": {
	        "Name": "mongo-roomboo",
	        "EndpointID": "84fc41e50ce4f7d24d90774f5f50bc710b5250d71afb87174f0ce511cbda457d",
	        "MacAddress": "02:42:ac:11:00:02",
	        "IPv4Address": "172.17.0.2/16",
	        "IPv6Address": ""
	    }
	},
----

== Perfiles de ejecución

[options="headers"]
|===
|Nombre        | Descripción
|`local`       | Perfil local de la aplicación.
|`unsecured`   | Deshabilita la seguridad basada en JWT.
|`mail`        | Habilita el envío de notificaciones por correo.
|===

== Stack

* Spring Boot
* MongoDB
* Hateoas
* JWT

== Referencias

* https://github.com/labcabrera/roomboo/wiki/Montando-el-proyecto[Guia para montar el proyecto en local]
* https://github.com/labcabrera/roomboo/wiki/Modelo-de-dominio[Modelo de la aplicación]
* https://github.com/labcabrera/roomboo/wiki/Estructura-del-proyecto[Estructura del proyecto]
* https://github.com/labcabrera/roomboo/wiki/Sistema-de-notificaciones-por-correo[Notificaciones por correo]
