app:
  env:
    jwt:
      authorization:
        path: /auth
      secret: changeit
      expiration: 1

spring:
  application:
    name: roomboo
  data:
    mongodb:
      uri: mongodb://localhost/roomboo
  jackson:
    default-property-inclusion: non_null

management:
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  level:
    org.lab.roomboo: DEBUG
    org.springframework: INFO
    springfox: WARN