spring:
  profiles:
    active: local,mail,force-initialization
    #active: local,unsecured
  application:
    name: roomboo-api
  jackson:
    default-property-inclusion: non_null


logging:
  level:
    root: ${LOG_LEVEL:INFO}
    org.lab.roomboo: ${LOG_LEVEL:DEBUG}
  file: ${LOG_FILE:/var/log/roomboo/${spring.application.name}.log}
  file.max-size: 1Mb
  file.max-history: 25

server:
  port: ${PORT:8080}
    
app:
  env:
    jwt:
      authorization:
        path: /auth
      secret: changeit
      expiration: 180
    reserve:
      minuteMultiplier: 15
    mail:
      enabled: false      
    token:
      reserve:
        expiration: 1440
        redirect-uri: https://www.google.com/?q=reserveConfirmedOk
        cancelation-redirect-uri: https://www.google.com/?q=roomboo%20cancelled
      user-register:
        expiration: 1440
        redirect-uri: https://www.google.com/?q=userCreatedOk
    security:
      unsecured:
        paths: '/swagger-ui.html,/v2/api-docs,/swagger-resources/**,/webjars/**,/v1/booking/accept/**,/v1/users/accept/**'
    contact:
      email: support@roomboo.org
    initialization:
      force: false

---

spring:
  profiles: local
  data:
    mongodb:
      uri: mongodb://${ENV_MONGO_HOST:localhost}/roomboo

--- # Disables JWT security

spring:
  profiles: unsecured
  autoconfigure:
    exclude: org.lab.roomboo.jwt.RoombooJwtAutoconfiguration,org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

--- # Enables email confirmation support

spring:
  profiles: mail
app:
  env:
    mail:
      enabled: true
      smtp:
        username: ${ENV_SMTP_USERNAME:}
        password: ${ENV_SMTP_PASSWORD:}
        host: ${ENV_SMTP_HOST:smtp.gmail.com}
        port: ${ENV_SMTP_PORT:587}
        debug: true

--- # Load initial data on application start

spring:
  profiles: force-initialization
app:
  env:
    initialization:
      force: true

--- # Enables all actuator endpoints

spring:
  profiles: actuator
management:
  endpoints:
    web:
      exposure:
        include: '*'
    