spring:
  data:
    mongodb:
      uri: mongodb://localhost/roomboo
  jackson:
    default-property-inclusion: non_null

management:
  endpoints:
    web:
      exposure:
        include: '*'





logging:
  level:
    org.lab.roomboo: DEBUG
    org.springframework: INFO
    springfox: WARN