spring:
  profiles:
    #active: local
    active: local,unsecured,force-initialization
  application:
    name: roomboo
  jackson:
    default-property-inclusion: non_null

management:
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  level:
    org.lab.roomboo: DEBUG
    org.springframework: INFO
    springfox: WARN

server:
  port: ${ENV_PORT:8080}
    
app:
  env:
    jwt:
      authorization:
        path: /auth
      secret: changeit
      expiration: 180
    initialization:
      force: false

---
spring:
  profiles: local
  data:
    mongodb:
      uri: mongodb://${ENV_MONGO_HOST:localhost}/roomboo
---
spring:
  profiles: unsecured
  autoconfigure:
    exclude: org.lab.roomboo.jwt.RoombooJwtAutoconfiguration,org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
---
spring:
  profiles: force-initialization
app:
  env:
    initialization:
      force: true
---
spring:
  profiles: live
logging:
  level:
    org.lab.roomboo: WARN
    org.springframework: WARN
    org.apache: WARN
    org.mongodb: WARN
    springfox: WARN
    