spring:
  data:
    mongodb:
      uri: mongodb://localhost/roomboo

management:
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  level:
    org.lab.roomboo: DEBUG
    org.springframework: INFO
    springfox: WARN